apiVersion: apps/v1
kind: Deployment
metadata:
 name: cloudpro-health-deployment
spec:
 replicas: 3 
 selector:
   matchLabels:
     app: cloudpro-health 
template:
   metadata: 
      labels:
        app: cloudpro-health 
spec:
  containers:
  - name: cloudpro-health  
    image: nginx:latest
ports:
- containerPort: 80
